/**
 * Created by OXOYO on 2017/4/5.
 * types.js
 */

export const SET_FLOWCHART_TREE_DATA = 'SET_FLOWCHART_TREE_DATA'
export const SET_FLOWCHART_CANVAS_DATA = 'SET_FLOWCHART_CANVAS_DATA'
export const UPDATE_FLOWCHART_CANVAS_STATUS = 'UPDATE_FLOWCHART_CANVAS_STATUS'
export const UPDATE_FLOWCHART_CANVAS_FORM_DATA = 'UPDATE_FLOWCHART_CANVAS_FORM_DATA'
export const SET_FLOWCHART_CANVAS_NODE_LIST = 'SET_FLOWCHART_CANVAS_NODE_LIST'
export const UPDATE_FLOWCHART_CANVAS_NODE_LIST = 'UPDATE_FLOWCHART_CANVAS_NODE_LIST'
export const EMPTY_FLOWCHART_CANVAS_NODE_LIST = 'EMPTY_FLOWCHART_CANVAS_NODE_LIST'
export const SET_FLOWCHART_CANVAS_LINK_LIST = 'SET_FLOWCHART_CANVAS_LINK_LIST'
export const UPDATE_FLOWCHART_CANVAS_LINK_LIST = 'UPDATE_FLOWCHART_CANVAS_LINK_LIST'
export const EMPTY_FLOWCHART_CANVAS_LINK_LIST = 'EMPTY_FLOWCHART_CANVAS_LINK_LIST'
export const EMPTY_FLOWCHART_CANVAS = 'EMPTY_FLOWCHART_CANVAS'
export const UPDATE_FLOWCHART_CONTEXTMENU = 'UPDATE_FLOWCHART_CONTEXTMENU'
export const UPDATE_FLOWCHART_CANVAS_ZOOM = 'UPDATE_FLOWCHART_CANVAS_ZOOM'
export const UPDATE_FLOWCHART_FULLSCREEN = 'UPDATE_FLOWCHART_FULLSCREEN'
export const UPDATE_FLOWCHART_CANVAS_NODE_OPTIONS = 'UPDATE_FLOWCHART_CANVAS_NODE_OPTIONS'
export const UPDATE_FLOWCHART_CANVAS_NODE_OPTIONS_LIST = 'UPDATE_FLOWCHART_CANVAS_NODE_OPTIONS_LIST'
export const UPDATE_FLOWCHART_CANVAS_NODE_CONTAINER = 'UPDATE_FLOWCHART_CANVAS_NODE_CONTAINER'
export const UPDATE_FLOWCHART_SAVE_ACTION_MODAL = 'UPDATE_FLOWCHART_SAVE_ACTION_MODAL'
export const UPDATE_FLOWCHART_TOOLBAR_BUTTONS = 'UPDATE_FLOWCHART_TOOLBAR_BUTTONS'
export const UPDATE_FLOWCHART_TOOLBAR_ACTION = 'UPDATE_FLOWCHART_TOOLBAR_ACTION'

export const GET_MODULE_TREE_SUCCESS = 'GET_MODULE_TREE_SUCCESS'
export const GET_MODULE_TREE_FAIL = 'GET_MODULE_TREE_FAIL'
